[package]
authors     = { workspace = true }
description = "Circuit parachain runtime"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "circuit-mock-runtime"
repository  = { workspace = true }
version     = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39" }

[dependencies]
codec       = { workspace = true, default-features = true, package = "parity-scale-codec"  }
hex-literal = { version = "0.3" }
log         = { version = "0.4" }
scale-info  = { workspace = true }
serde       = { version = "1.0", optional = true, features = [ "derive" ] }

t3rn-abi        = { path = "../../types/abi" }
t3rn-primitives = { path = "../../primitives" }
t3rn-types      = { path = "../../types" }

circuit-runtime-pallets = { path = "../common-pallets" }
circuit-runtime-types   = { path = "../common-types" }

# Substrate Dependencies
frame-executive              = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
frame-support                = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
frame-system                 = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
node-primitives              = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }

sp-api              = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-block-builder    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-consensus-aura   = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-core             = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-inherents        = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-offchain         = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-runtime          = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-session          = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-std              = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-trie             = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-version          = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }

pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39" }

# Mock only
sp-io = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
