[package]
name = "t3rn-parachain-primitives"
version = "0.1.0"
authors = ["t3rn ltd. <team@t3rn.io>"]
edition = "2018"
homepage = "https://t3rn.io"
license = "Apache 2.0"
repository = "https://github.com/t3rn/t3rn/"
description = "A crate that hosts a common definitions that are relevant for the all t3rn pallets."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# This crate should not rely on any of the frame primitives.
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]  }
sp-std =  { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12', default-features = false }
sp-version =  { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12', default-features = false }
sp-core =  { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12', default-features = false }
sp-io =  { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12', default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12', default-features = false }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12' }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12' }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.12' }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
hex-literal = { version = '0.3.1'}
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"serde/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-core/std",
	"sp-version/std",
	"sp-io/std",
	"pallet-sudo/std",
	"frame-system/std",
	"frame-support/std",
]
