[package]
authors     = { workspace = true }
description = "t3rn portal"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-portal-rpc"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec               = { workspace = true, package = "parity-scale-codec" }
jsonrpc-core        = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive      = "18.0.0"

pallet-portal-rpc-runtime-api = { path = "runtime-api" }
sp-api                        = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-blockchain                 = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-core                       = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-rpc                        = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-runtime                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
