[package]
authors     = [ "Parity Technologies <admin@parity.io>", "devs @ t3rn" ]
description = "Primitive EVM abstractions for Substrate."
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "fp-evm"
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
sp-core = { workspace = true }
sp-std  = { workspace = true }

frontier-fp-evm = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false, package = "fp-evm" }

[features]
default = [ "std" ]
std     = [ "sp-core/std", "sp-std/std", "frontier-fp-evm/std" ]
