[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'node/service',
    'pallets/*',
    'primitives',
    'primitives/src/bridges/finality',
    'primitives/src/bridges/headers',
    'primitives/src/bridges/utils',
    'runtime/*',
]
exclude = []
