[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'node/service',
    'pallets/*',
    'primitives',
    'runtime/parachain',
    'runtime/standalone',
    'test-utils'
]
exclude = [
    'pallets/beefy-merkle-tree',
    'pallets/beefy-mmr-pallet',
]
