[settings]
timeout = 1000

[relaychain]
default_image = "parity/polkadot:v0.9.27"
chain = "rococo-local"
default_command = "./bin/polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9900
extra_args = [ "-lparachain=debug" ]

[[relaychain.nodes]]
name = "bob"
validator = true
extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 1
addToGenesis = true
cumulus_based = true
chain = "statemine-local"

[[parachains.collators]]
name = "statemine-collator01"
image = "docker.io/parity/polkadot-parachain:latest"
command = "polkadot-parachain"
ws_port = 9910
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains.collators]]
name = "statemine-collator02"
image = "docker.io/parity/polkadot-parachain:latest"
command = "polkadot-parachain"
ws_port = 9911
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 2
addToGenesis = true
cumulus_based = true
chain = "rococo"

[[parachains.collators]]
name = "t0rn-collator01"
image = "t3rn/t0rn-collator:v1.1.0-rc.1"
command = "/usr/local/bin/circuit-collator"
ws_port = 9920
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains.collators]]
name = "t0rn-collator02"
image = "t3rn/t0rn-collator:v1.1.0-rc.1"
command = "/usr/local/bin/circuit-collator"
ws_port = 9921
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 3
addToGenesis = true
cumulus_based = true
chain = ""

[[parachains.collators]]
name = "t0rn-collator01"
image = "t3rn/t0rn-collator:v1.1.0-rc.1"
command = "/usr/local/bin/circuit-collator"
ws_port = 9930
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains.collators]]
name = "t0rn-collator02"
image = "t3rn/t0rn-collator:v1.1.0-rc.1"
command = "/usr/local/bin/circuit-collator"
ws_port = 9931
args = ["--log=xcm=trace,pallet-assets=trace"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

[[hrmp_channels]]
sender = 1
recipient = 2
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 1
recipient = 3
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2
recipient = 1
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2
recipient = 3
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3
recipient = 1
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3
recipient = 2
max_capacity = 8
max_message_size = 512