[package]
authors     = { workspace = true }
description = "Cross-chain DNS RPC"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-xdns-rpc"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec      = { workspace = true, package = "parity-scale-codec" }
jsonrpsee = { version = "0.14.0", features = [ "server", "macros" ] }

pallet-xdns-rpc-runtime-api = { path = "runtime-api" }
sp-api                      = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-blockchain               = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-core                     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-rpc                      = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-runtime                  = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
t3rn-primitives             = { path = "../../../primitives" }
