[package]
name = "pallet-runtime-gateway-rpc-runtime-api"
version = "0.1.0"
authors = ["t3rn Ltd."]
edition = "2018"
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
serde = { version = "1", features = ["derive"], optional = true }
bitflags = { version = "1" }

# Substrate Dependencies

sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-core/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"serde",
]
