[package]
authors     = { workspace = true }
description = "Implements t3rn x-chain executors staking."
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-executors"
publish     = false
repository  = "https://github.com/t3rn/t3rn"
version     = "1.0.0-rc.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec      = { workspace = true, package = "parity-scale-codec" }
log        = { workspace = true }
scale-info = { workspace = true }
serde      = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support      = { workspace = true }
frame-system       = { workspace = true }

sp-runtime = { workspace = true }
sp-std     = { workspace = true }

t3rn-abi            = { default-features = false, path = "../../types/abi", features = [ "runtime" ] }
t3rn-primitives     = { default-features = false, path = "../../primitives" }
t3rn-sdk-primitives = { version = "=0.1.1-rc.4", default-features = false }
t3rn-types          = { path = "../../types", default-features = false }

substrate-abi = { workspace = true }
xp-channel    = { workspace = true, features = [ "frame" ] }
xp-format     = { workspace = true }
xs-channel    = { workspace = true }

pallet-circuit = { path = "../circuit", default-features = true }
# pallet-xbi-portal-enter = { git = "https://github.com/t3rn/xbi", version = "0.9.19", default-features = true 

[dev-dependencies]
similar-asserts = "1.1.0"

sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-io   = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

hex-literal = "0.3"

circuit-mock-runtime    = { path = "../../runtime/mock" }
circuit-runtime-pallets = { path = "../../runtime/common-pallets" }
circuit-runtime-types   = { path = "../../runtime/common-types" }

[features]
default = [ "std" ]
std = [
  "log/std",
  "serde/std",
  "codec/std",
  "pallet-circuit/std",
  "t3rn-abi/std",
  "t3rn-sdk-primitives/std",
  "t3rn-types/std",
  "pallet-circuit/try-runtime",
  "t3rn-abi/try-runtime",
  "pallet-circuit/runtime-benchmarks",
  "scale-info/std",
  "sp-runtime/std",
  "substrate-abi/std",
  "sp-std/std",
  "t3rn-primitives/std",
  "frame-support/std",
  "frame-system/std",
  "xp-channel/std",
  "xp-channel/frame-std",
  "xs-channel/std",
  "xp-format/std",
]

runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "pallet-circuit/runtime-benchmarks",
]
try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime", "pallet-circuit/try-runtime", "t3rn-abi/try-runtime", "sp-runtime/try-runtime" ]
