[package]
edition    = { workspace = true }
homepage   = { workspace = true }
license    = { workspace = true }
name       = "precompile-util"
repository = { workspace = true }
version    = { workspace = true }

[dependencies]
pallet-3vm-evm            = { path = "../..", default-features = false, package = "pallet-evm" }
pallet-3vm-evm-primitives = { path = "../../primitives", default-features = false, package = "fp-evm" }
portal-precompile                  = { path = "../portal", default-features = false }

sp-core                   = { workspace = true }
sp-std                    = { workspace = true }

pallet-evm-precompile-3vm-dispatch = { path = "../3vm-dispatch", default-features = false }
pallet-evm-precompile-blake2       = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-bn128        = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-curve25519   = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-dispatch     = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-ed25519      = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-modexp       = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-sha3fips     = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }
pallet-evm-precompile-simple       = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.39", default-features = false }

[features]
default = [ "std" ]
std = [
  "sp-core/std",
  "sp-std/std",
  "pallet-3vm-evm-primitives/std",
  "pallet-3vm-evm/std",
  "portal-precompile/std",
  "pallet-evm-precompile-3vm-dispatch/std",
  "pallet-evm-precompile-blake2/std",
  "pallet-evm-precompile-bn128/std",
  "pallet-evm-precompile-curve25519/std",
  "pallet-evm-precompile-dispatch/std",
  "pallet-evm-precompile-ed25519/std",
  "pallet-evm-precompile-modexp/std",
  "pallet-evm-precompile-sha3fips/std",
  "pallet-evm-precompile-simple/std",
]
