[package]
authors     = [ "t3rn" ]
description = "RPC interface for the contracts registry pallet."
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-contracts-registry-rpc"
readme      = { workspace = true }
repository  = { workspace = true }
version     = "1.0.0-aplha.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec               = { workspace = true, package = "parity-scale-codec" }
jsonrpc-core        = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive      = { workspace = true }

serde = { version = "1.0", features = [ "derive" ] }

frame-system                              = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-contracts-registry                 = { path = ".." }
pallet-contracts-registry-rpc-runtime-api = { path = "runtime-api" }
sp-api                                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-blockchain                             = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-core                                   = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-rpc                                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
sp-runtime                                = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
