[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "on-chain composable contracts registry"
edition     = "2018"
homepage    = "https://t3rn.io"
license     = "Apache 2.0"
name        = "pallet-bsc-fv"
readme      = "README.md"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.0.0-alpha.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
frame-support = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19"}
frame-system = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
frame-benchmarking = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19", optional = true }
ethereum-types      = { version = "0.13.1", features = ["rlp", "codec"], default-features = false }
codec               = { package = "parity-scale-codec", version = "3", features = [ "derive" ], default-features = false }
rlp                 = { version = "0.5.1", default-features = false }
keccak-hash         = { version = "0.5.1", default-features = false }
eth_trie            = { git = "https://github.com/petscheit/eth-trie.rs", default-features = false }
k256                = { version = "0.10.4", default-features = false, features = ["ecdsa"] }
elliptic-curve = { version = "0.11.12", default-features = false }
generic-array = { version = "0.14.5", default-features = false }
sp-std = "4.0.0"
log          = { version = "0.4.14", default-features = false }

[dev-dependencies]
sp-core = { default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-io = { default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-runtime = { default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
]

runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
