[package]
authors     = { workspace = true }
description = "Primitives for a 3VM enabled EVM RPC."
edition     = { workspace = true }
license     = { workspace = true }
name        = "pallet-evm-rpc-runtime-api"
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
ethereum       = { version = "0.12.0", default-features = false, features = [ "with-codec" ] }
ethereum-types = { version = "0.13.1", default-features = false }

codec      = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { workspace = true }
sp-api     = { version = "4.0.0-dev", workspace = true }
sp-core    = { version = "6.0.0", workspace = true }
sp-io      = { version = "6.0.0", workspace = true }
sp-runtime = { version = "6.0.0", workspace = true }
sp-std     = { version = "4.0.0", workspace = true }

fp-evm = { path = "../../primitives", default-features = false }

[features]
default = [ "std" ]
std     = [ "ethereum/std", "ethereum-types/std", "codec/std", "scale-info/std", "sp-api/std", "sp-core/std", "sp-io/std", "sp-runtime/std", "sp-std/std", "fp-evm/std" ]
