[package]
authors     = { workspace = true }
description = "Node-specific RPC methods for interaction with evm contracts."
edition     = { workspace = true }
license     = { workspace = true }
name        = "pallet-evm-rpc"
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec      = { workspace = true, package = "parity-scale-codec" }
jsonrpsee = { version = "0.14.0", features = [ "server", "macros" ] }
serde     = { version = "1", features = [ "derive" ] }

# Substrate Dependencies
pallet-evm-primitives      = { path = "../primitives", package = "fp-evm" }
pallet-evm-rpc-runtime-api = { path = "runtime-api" }
sp-api                     = { workspace = true }
sp-blockchain              = { workspace = true }
sp-core                    = { workspace = true }
sp-rpc                     = { workspace = true }
sp-runtime                 = { workspace = true }

[dev-dependencies]
serde_json = "1"
