[package]
name = "circuit-rpc-runtime-api"
version = "0.1.0"
authors = ["MaciejBaj <maciej@maciejbaj.com>"]
edition = "2018"
homepage = "https://t3rn.io"
license = "Apache 2.0"
repository = "https://github.com/t3rn/t3rn/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"], default-features = false }
frame-system = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8", default-features=false }
sp-api ={ git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8', default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8', default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8', default-features = false }
#pallet-contracts-registry-rpc-runtime-api = { version = "0.1.0", path = "../../pallets/contracts-registry/rpc/runtime-api", default-features = false }
t3rn-primitives = { version = "0.1.0", path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
#	"pallet-contracts-registry-rpc-runtime-api/std",
	"t3rn-primitives/std",
]
