[package]
authors     = [ "Parity Technologies <admin@parity.io>" ]
description = "Runtime API definition required by Contracts RPC extensions."
edition     = { workspace = true }
homepage    = "https://substrate.io"
license     = { workspace = true }
name        = "pallet-contracts-rpc-runtime-api"
readme      = { workspace = true }
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true }

# Substrate Dependencies
pallet-contracts-primitives = { version = "5.0.0", default-features = false, path = "../../primitives" }
sp-api                      = { workspace = true }
sp-runtime                  = { workspace = true }
sp-std                      = { workspace = true }

[features]
default = [ "std" ]
std     = [ "sp-api/std", "codec/std", "scale-info/std", "sp-std/std", "sp-runtime/std", "pallet-contracts-primitives/std" ]
