[package]
authors     = { workspace = true }
description = "on-chain composable contracts registry"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-contracts-registry"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec      = { package = "parity-scale-codec", version = "3", default-features = false }
log        = { version = "0.4.14", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = [ "derive" ] }
serde      = { version = "1.0", default-features = false, optional = true, features = [ "derive" ] }

frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', optional = true }
frame-support      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
frame-system       = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }

sp-io      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-std     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }

pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }

t3rn-primitives = { default-features = false, path = "../../primitives" }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }

circuit-mock-runtime = { path = "../../runtime/mock" }

[features]
default = [ "std" ]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame-support/std",
  "frame-system/std",
  "log/std",
  "pallet-timestamp/std",
  "serde/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "t3rn-primitives/std",
  "scale-info/std",
]
try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime", "pallet-timestamp/try-runtime" ]
