[package]
authors     = [ "Parity Technologies <admin@parity.io>" ]
description = "FRAME pallet for WASM contracts"
edition     = "2021"
homepage    = "https://substrate.io"
include     = [ "src/**/*", "README.md", "CHANGELOG.md" ]
license     = "Apache-2.0"
name        = "pallet-contracts-parity"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
bitflags              = "1.3"
codec                 = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [ "derive", "max-encoded-len" ] }
impl-trait-for-tuples = "0.2"
log                   = { version = "0.4", default-features = false }
scale-info            = { version = "2.1.1", default-features = false, features = [ "derive" ] }
serde                 = { version = "1", optional = true, features = [ "derive" ] }
smallvec              = { version = "1", default-features = false, features = [ "const_generics" ] }
wasm-instrument       = { version = "0.4", default-features = false }
wasmi                 = { version = "0.20", default-features = false }
wasmparser            = { package = "wasmparser-nostd", version = "0.91", default-features = false }

# Only used in benchmarking to generate random contract code
rand     = { version = "0.8", optional = true, default-features = false }
rand_pcg = { version = "0.3", optional = true }

# Substrate Dependencies
frame-benchmarking          = { workspace = true, optional = true }
frame-support               = { workspace = true }
frame-system                = { workspace = true }
pallet-contracts-primitives = { default-features = false, path = "../contracts/primitives" }
pallet-contracts-proc-macro = { workspace = true }
sp-api                      = { workspace = true }
sp-core                     = { workspace = true }
sp-io                       = { workspace = true }
sp-runtime                  = { workspace = true }
sp-std                      = { workspace = true }

[dev-dependencies]
array-bytes       = "4.1"
assert_matches    = "1"
env_logger        = "0.9"
pretty_assertions = "1"
wat               = "1"

# Substrate Dependencies
pallet-balances                   = { workspace = true }
pallet-randomness-collective-flip = { workspace = true }
pallet-timestamp                  = { workspace = true }
pallet-utility                    = { workspace = true }
sp-keystore                       = { workspace = true }

[features]
default = [ "std" ]
runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks", "rand", "rand_pcg" ]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"wasm-instrument/std",
	"wasmi/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-proc-macro/full",
	"log/std",
	"rand/std",
	"wasmparser/std",
]
try-runtime = [ "frame-support/try-runtime" ]
