[package]
authors     = [ "Parity Technologies <admin@parity.io>", "t3rn ltd. <team@t3rn.io>" ]
description = "FRAME EVM contracts pallet that is t3rn 3VM enabled"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-evm"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
evm             = { workspace = true }
hex             = { workspace = true, features = [ "serde" ] }
log             = { workspace = true }
primitive-types = { workspace = true }
rlp             = { workspace = true }
serde           = { optional = true, workspace = true }
sha3            = { workspace = true }

codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true }
sp-core    = { workspace = true }
sp-io      = { workspace = true }
sp-runtime = { workspace = true }
sp-std     = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support      = { workspace = true }
frame-system       = { workspace = true }
pallet-timestamp   = { workspace = true }

fp-evm = { path = "primitives", default-features = false }

# t3rn dependencies
t3rn-primitives     = { default-features = false, path = "../../primitives" }
t3rn-sdk-primitives = { version = "=0.1.1-rc.4", default-features = false }
#t3rn-sdk-primitives = { path = "../../../../sdk/crates/primitives", default-features = false }

[dev-dependencies]
hex-literal = "*"
serde_json  = { version = "1.0.34" }

# Substrate Dependencies
pallet-assets                     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
pallet-balances                   = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
pallet-sudo                       = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
pallet-utility                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }

# t3rn dependencies
pallet-3vm                       = { path = "../3vm" }
pallet-account-manager           = { path = "../account-manager" }
pallet-circuit                   = { path = "../circuit" }
pallet-contracts-registry        = { path = "../contracts-registry" }
pallet-grandpa-finality-verifier = { path = "../../finality-verifiers/grandpa" }
pallet-portal                    = { path = "../portal" }
pallet-xdns                      = { path = "../xdns" }

# TODO: automatically build fixtures, broken as we need to patch the k256 crate
## Solc dependencies
#ethers-solc = { git = "https://github.com/gakonst/ethers-rs.git" }

pallet-xbi-portal = { git = "https://github.com/t3rn/xbi", version = "0.3.0" }

[features]
default = [ "std" ]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "evm/std",
  "evm/with-serde",
  "hex/std",
  "log/std",
  "primitive-types/std",
  "rlp/std",
  "serde",
  "sha3/std",
  "codec/std",
  "scale-info/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-timestamp/std",
  "t3rn-primitives/std",
  "t3rn-sdk-primitives/std",
  "fp-evm/std",
]
