[package]
authors     = [ "Parity Technologies <admin@parity.io>", "t3rn ltd. <team@t3rn.io>" ]
description = "FRAME EVM contracts pallet that is t3rn 3VM enabled"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-evm"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
evm                   = { workspace = true }
impl-trait-for-tuples = { workspace = true }
log                   = { workspace = true }
primitive-types       = { workspace = true }

codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true }
sp-core    = { workspace = true }
sp-io      = { workspace = true }
sp-runtime = { workspace = true }
sp-std     = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support      = { workspace = true }
frame-system       = { workspace = true }

fp-account = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v1.0.0", default-features = false }
fp-evm     = { path = "primitives", default-features = false }

# t3rn dependencies
t3rn-primitives = { default-features = false, path = "../../primitives" }

[features]
default = [ "std" ]
runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks", "frame-support/runtime-benchmarks", "frame-system/runtime-benchmarks", "sp-runtime/runtime-benchmarks" ]
std = [
  "evm/std",
  "evm/with-serde",
  "log/std",
  "primitive-types/std",
  "codec/std",
  "scale-info/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "frame-support/std",
  "frame-system/std",
  "t3rn-primitives/std",
  "fp-evm/std",
  "fp-account/std",
]
