[package]
authors     = { workspace = true }
description = "circuit implements fail-safe interoperable execution based on open-market mechanics and trust-free remote chain inclusion proofs"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-circuit"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec            = { workspace = true, package = "parity-scale-codec" }
log              = { workspace = true }
pallet-timestamp = { workspace = true }
scale-info       = { workspace = true }
serde            = { workspace = true, optional = true, features = [ "derive" ] }
num-traits       = { version = "0.2", default-features = false }

frame-benchmarking = { workspace = true, optional = true }
frame-support      = { workspace = true }
frame-system       = { workspace = true }
sp-core            = { workspace = true }
sp-io              = { workspace = true }
sp-runtime         = { workspace = true }
sp-std             = { workspace = true }
sp-trie            = { workspace = true }

pallet-xbi-portal   = { workspace = true }
t3rn-abi            = { default-features = false, path = "../../types/abi", features = [ "runtime" ] }
t3rn-primitives     = { default-features = false, path = "../../primitives" }
t3rn-sdk-primitives = { version = "=0.1.1-rc.4", default-features = false }
t3rn-types          = { default-features = false, path = "../../types", features = [ "runtime" ] }

[dev-dependencies]
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
hex                             = "0.4.2"
hex-literal                     = "0.2.1"
pallet-authorship               = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39' }
pallet-babe                     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-offences                 = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-session                  = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-staking                  = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-staking-reward-curve     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-transaction-payment      = { workspace = true }
serde_json                      = "1.0.41"
sp-consensus-aura               = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39' }
sp-consensus-babe               = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39' }
sp-consensus-vrf                = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39' }
sp-finality-grandpa             = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39' }
sp-staking                      = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39' }

# Needed because of testing features
pallet-grandpa-finality-verifier = { path = "../../finality-verifiers/grandpa", features = [ "testing" ] }

circuit-mock-runtime    = { path = "../../runtime/mock" }
circuit-runtime-pallets = { path = "../../runtime/common-pallets" }
circuit-runtime-types   = { path = "../../runtime/common-types" }

[features]
default = [ "std" ]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "pallet-xbi-portal/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "log/std",
  "pallet-timestamp/std",
  "scale-info/std",
  "serde/std",
  "sp-core/std",
  "sp-io/std",
  "sp-trie/std",
  "sp-runtime/std",
  "sp-std/std",
  "t3rn-primitives/std",
  "t3rn-types/std",
  "t3rn-abi/std",
  "t3rn-sdk-primitives/std",
  "pallet-xbi-portal/std",
]
try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime", "pallet-timestamp/try-runtime", "t3rn-abi/try-runtime", "sp-runtime/try-runtime" ]
test-skip-verification = [  ]
