[package]
name = "flipper"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc5", default-features = false }
ink_metadata = { version = "3.0.0-rc5", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc5", default-features = false }
ink_storage = { version = "3.0.0-rc5", default-features = false }
ink_lang = { version = "3.0.0-rc5", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }


[lib]
name = "flipper"
path = "lib.rs"
crate-type = ["cdylib"]

[package.metadata]
composables = ["runtime_demo_storage", "flipper_contract", "call_flipper"]
deploy = [ { compose = "flipper_contract", vm = "pallet-contracts", url = "wss://dev.net.t3rn.io" } ]

[features]
default = ["std"]
runtime_demo_storage = []
flipper_contract = []
call_flipper = []

std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
]
ink-as-dependency = []
