[package]
authors     = [ "Parity Technologies <admin@parity.io>", "t3rn ltd. <team@t3rn.io>" ]
description = "FRAME pallet for WASM contracts"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-contracts"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
bitflags              = { workspace = true }
codec                 = { workspace = true, package = "parity-scale-codec" }
hex                   = { workspace = true }
impl-trait-for-tuples = "0.2"
log                   = { workspace = true }
scale-info            = { workspace = true }
serde                 = { workspace = true, optional = true, features = [ "derive" ] }
smallvec              = { workspace = true }
wasm-instrument       = { workspace = true }
wasmi                 = { workspace = true }
wasmparser            = { workspace = true }

# Enabled by benchmarks
frame-benchmarking = { workspace = true, optional = true }
rand               = { workspace = true, optional = true }
rand_pcg           = { workspace = true, optional = true }

# Substrate Dependencies
frame-support = { workspace = true }
frame-system  = { workspace = true }

pallet-contracts-primitives = { default-features = false, path = "primitives" }
pallet-contracts-proc-macro = { workspace = true }
sp-api                      = { workspace = true }
sp-core                     = { workspace = true }
sp-io                       = { workspace = true }
sp-runtime                  = { workspace = true }
sp-std                      = { workspace = true }

# t3rn dependencies
t3rn-primitives     = { default-features = false, path = "../../primitives" }
t3rn-sdk-primitives = { version = "=0.1.1-rc.4", default-features = false }
#t3rn-sdk-primitives = { path = "../../../../sdk/crates/primitives", default-features = false }

[dev-dependencies]
assert_matches    = "1"
env_logger        = "0.9"
glob              = "0.3"
hex-literal       = "0.3"
pretty_assertions = "1"
serde_json        = "1.0.81"
wat               = "1"

# Substrate Dependencies
pallet-assets                     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-balances                   = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39', package = "pallet-insecure-randomness-collective-flip" }
pallet-sudo                       = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-timestamp                  = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }
pallet-utility                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }

# t3rn dependencies
pallet-3vm                       = { path = "../3vm" }
pallet-account-manager           = { path = "../account-manager" }
pallet-circuit                   = { path = "../circuit" }
pallet-contracts-registry        = { path = "../contracts-registry" }
pallet-grandpa-finality-verifier = { path = "../../finality-verifiers/grandpa" }
pallet-portal                    = { path = "../portal" }
pallet-xdns                      = { path = "../xdns" }

sp-keystore = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.39' }

pallet-xbi-portal = { workspace = true, default-features = true }

[features]
default = [ "std" ]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "rand",
  "rand_pcg",
  "unstable-interface",
]
std = [
  "serde/std",
  "codec/std",
  "scale-info/std",
  "hex/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-io/std",
  "sp-api/std",
  "sp-std/std",
  "frame-support/std",
  "frame-system/std",
  "wasm-instrument/std",
  "wasmi/std",
  "wasmparser/std",
  "pallet-contracts-primitives/std",
  "pallet-contracts-proc-macro/full",
  "log/std",
  "rand/std",
  "t3rn-primitives/std",
  "t3rn-sdk-primitives/std",
]
try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime", "sp-runtime/try-runtime" ]
# Make contract callable functions marked as __unstable__ available. Do not enable
# on live chains as those are subject to change.
unstable-interface = [  ]
