[package]
authors     = [ "Parity Technologies <admin@parity.io>" ]
description = "Node-specific RPC methods for interaction with contracts."
edition     = { workspace = true }
homepage    = "https://substrate.io"
license     = { workspace = true }
name        = "pallet-contracts-rpc"
readme      = { workspace = true }
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec               = { workspace = true, default-features = true }
jsonrpc-core        = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive      = "18.0.0"
jsonrpsee           = { version = "0.14.0", features = [ "server", "macros" ] }
serde               = { version = "1", features = [ "derive" ] }

# Substrate Dependencies
pallet-contracts-primitives      = { version = "5.0.0", path = "../primitives" }
pallet-contracts-rpc-runtime-api = { version = "4.0.0-dev", path = "runtime-api" }
sp-api                           = { workspace = true }
sp-blockchain                    = { workspace = true }
sp-core                          = { workspace = true }
sp-rpc                           = { workspace = true }
sp-runtime                       = { workspace = true }

[dev-dependencies]
serde_json = "1"
