[package]
name = "pallet-maintenance-mode"
authors = { workspace = true }
description = "Puts a FRAME-based runtime into maintenance mode where restricted interactions are allowed."
edition = "2021"
version = "0.1.0"

[dependencies]

# Local
#xcm-primitives = { workspace = true, optional = true }

# Crates.io
log = { version = "0.4", default-features = false }

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39', default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39', default-features = false }
parity-scale-codec = { version = "3.2.2", package = "parity-scale-codec", features = [ "derive" ], default-features = false }
scale-info = { version = "2.1.1", features = [ "derive" ], default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39', default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39', default-features = false }

# Cumulus
#cumulus-primitives-core = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v0.9.39', default-features = false, optional = true }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39', features = [ "std" ] }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.39', features = [ "std" ] }

[features]
default = [ "std" ]
std = [
#	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [ "frame-support/try-runtime" ]
#xcm-support = [ "cumulus-primitives-core", "xcm-primitives" ]
xcm-support = [ ]
