[package]
name = "pallet-maintenance-mode"
authors = { workspace = true }
description = "Puts a FRAME-based runtime into maintenance mode where restricted interactions are allowed."
edition = "2021"
version = "0.1.0"

[dependencies]

# Crates.io
log = { workspace = true }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }


[dev-dependencies]
sp-core = { workspace = true, features = [ "std" ] }
sp-io = { workspace = true, features = [ "std" ] }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [ "frame-support/try-runtime" ]
xcm-support = [ ]
